name: azure-aca-aspire-ai-starter
metadata:
  template: azure-aca-aspire-ai-starter@0.1.0

env:
  AZURE_LOCATION: southindia

infra:
  provider: bicep
  path: infra

services:
  backend:
    project: ./src/backend
    host: containerapp
    language: dotnet
  frontend:
    project: ./src/frontend
    host: containerapp
    language: js
  worker:
    project: ./src/worker
    host: containerapp
    language: dotnet

pipeline:
  provider: github
